# GitHub workflow to add new or transferred issues to a specified project
name: Add Issues to Project

on:
  issues:
    # ***********************************************************************************
    # Feel free to customize this. Options are: opened, reopened, transferred, or labeled
    types: [opened, reopened, transferred]
    # ************************************************************************************

jobs:
  upload-issue: 
    name: Add Issue to Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # ***************************************************************
          # Change this to the project URL you want to send your issues to
          # GitHub Organization Project URL:
          # https://github.com/orgs/<org_name>/projects/<project_number>
          # GitHub User Project URL:
          # https://github.com/users/<GitHub_username>/projects/<project_number>
          project-url: https://github.com/orgs/<org_name>/projects/<project_number>
          # ***************************************************************

          # Be sure to add the PAT with the correct scope to the repository!
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
