# This is a basic workflow to help you get started with Actions

name: Add Issues to Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:[opened, reopened, transferred]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload-issue: 
    name: Add Issue to Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/IanSinColorado/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
